// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5MjFljwQCVf67daWyNsTjbONrIDTRl-I',
    appId: '1:788385310225:web:281374f5213d3f2f1773b0',
    messagingSenderId: '788385310225',
    projectId: 'sample-bf0ca',
    authDomain: 'sample-bf0ca.firebaseapp.com',
    storageBucket: 'sample-bf0ca.appspot.com',
    measurementId: 'G-EH3CJEPQ2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKtLf-aGvItoeYYIZ2ahAVTng5Sed2dA',
    appId: '1:788385310225:android:8fd4e98ff8ed33741773b0',
    messagingSenderId: '788385310225',
    projectId: 'sample-bf0ca',
    storageBucket: 'sample-bf0ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcNoi0ixBh7xOBtHLxv0ZA0RNfw3WmaA',
    appId: '1:788385310225:ios:68bef3d1c3f099191773b0',
    messagingSenderId: '788385310225',
    projectId: 'sample-bf0ca',
    storageBucket: 'sample-bf0ca.appspot.com',
    iosBundleId: 'com.example.userProfileManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcNoi0ixBh7xOBtHLxv0ZA0RNfw3WmaA',
    appId: '1:788385310225:ios:68bef3d1c3f099191773b0',
    messagingSenderId: '788385310225',
    projectId: 'sample-bf0ca',
    storageBucket: 'sample-bf0ca.appspot.com',
    iosBundleId: 'com.example.userProfileManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5WwmKgLr8bZWSSdE33DHQwQdS31LbJvE',
    appId: '1:788385310225:web:868cc5d1efc4d8ea1773b0',
    messagingSenderId: '788385310225',
    projectId: 'sample-bf0ca',
    authDomain: 'sample-bf0ca.firebaseapp.com',
    storageBucket: 'sample-bf0ca.appspot.com',
    measurementId: 'G-T48JB330RN',
  );
}
